# Generated by Django 4.2.4 on 2023-08-27 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='название')),
                ('slug', models.CharField(max_length=150, verbose_name='slug')),
                ('body', models.TextField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials_image')),
                ('date_of_create', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sign_of_pub', models.BooleanField(blank=True, default=False, null=True)),
                ('count_view', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
    ]
