# Generated by Django 4.2.4 on 2023-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_message_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mailing_time',
            field=models.TimeField(verbose_name='время  начала рассылки'),
        ),
    ]
