# Generated by Django 4.2.4 on 2023-08-29 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_message_mailing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='состояние'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время  начала рассылки'),
        ),
    ]
